base-url:
markdown: kramdown
paginate: 5
permalink: pretty
highlighter: pygments

gems:
  - jemoji

exclude: [ vendor, s3_website.yml, env.sample ]

navigation:
  - name: "Notes"
    url: "/"
  - name: "Projects"
    url: "http://philtr.github.io"
  - name: "About"
    url: "/about/"
  - name: "Contact"
    url: "/contact/"

paginate: 5
paginate_path: "/page/:num"

url: http://phillipridlen.com
email: p@rdln.net
