permalink: pretty
markdown: kramdown
highlighter: pygments

gems:
  - jekyll-assets

exclude: [ .asset-cache, vendor, s3_website.yml, env.sample, Gemfile, Gemfile.lock, README.md, circle.yml, spec ]

collections:
  - projects

navigation:
  - name: "Projects"
    url: "/projects/"
  - name: "Contact"
    url: "/contact/"
  - name: "About"
    url: "/about/"

url: https://phillipridlen.com
email: p@rdln.net
rss: https://feeds.feedburner.com/phillipridlen

assets:
  compress:
    css: true
    js: true
  digest: true
