base-url:
markdown: kramdown
paginate: 5
permalink: pretty
highlighter: pygments

gems:
  - jemoji

exclude: [ vendor, s3_website.yml, env.sample ]

navigation:
  - name: "Notes"
    url: "/"
  - name: "Open Source"
    url: "http://philtr.github.io"

paginate: 5
paginate_path: "notes/page/:num"

url: http://phillipridlen.com
email: p@rdln.net
