permalink: pretty
markdown: kramdown
highlighter: pygments

gems:
  - jekyll-assets

exclude: [ .asset-cache, vendor, s3_website.yml, env.sample, Gemfile, Gemfile.lock, README.md, circle.yml, spec ]

collections:
  - projects

navigation:
  - name: "Notes"
    url: "/notes/"
  - name: "Projects"
    url: "/projects/"
  - name: "About"
    url: "/about/"
  - name: "Contact"
    url: "/contact/"

paginate: 5
paginate_path: "/notes/page-:num"

url: http://phillipridlen.com
email: p@rdln.net
rss: http://feeds.feedburner.com/phillipridlen

assets:
  js_compressor: uglifier
  css_compressor: sass
