base-url:
markdown: kramdown
paginate: 5
permalink: pretty
highlighter: pygments

exclude: [ vendor ]

navigation:
  - name: "Notes"
    url: "/"
  - name: "Open Source"
    url: "http://philtr.github.io"

paginate: 5
paginate_path: "notes/page/:num"

url: http://phillipridlen.com
email: p@rdln.net
