base-url:
markdown: rdiscount
paginate: 5
permalink: pretty
pygments: true
rdiscount:
  extensions: [smart]

title: Phillip's Blog
tagline: "The Notes, Quotes, and Other Miscellany of Phillip T. Ridlen"
name: Phillip T. Ridlen
url: http://phillipridlen.com/
email: p@rdln.net
