permalink: /notes/:categories/:year/:month/:day/:title/

markdown: kramdown

highlighter: pygments

gems:
  - jemoji

exclude: [ vendor, s3_website.yml, env.sample, Gemfile, Gemfile.lock, README.md ]

collections:
  - projects

navigation:
  - name: "Notes"
    url: "/"
  - name: "Projects"
    url: "/projects/"
  - name: "About"
    url: "/about/"
  - name: "Contact"
    url: "/contact/"

paginate: 5
paginate_path: "/notes/page/:num"

url: http://phillipridlen.com
email: p@rdln.net
