base-url:
markdown: kramdown
paginate: 5
permalink: pretty
pygments: true

title: Phillip's Blog
tagline: "The Notes, Quotes, and Other Miscellany of Phillip T. Ridlen"
name: Phillip T. Ridlen
url: http://phillipridlen.com
email: p@rdln.net
