permalink: pretty
markdown: kramdown
highlighter: pygments

plugins:
  - jekyll-assets

exclude: [ .asset-cache, vendor, s3_website.yml, env.sample, Gemfile, Gemfile.lock, README.md, spec ]

collections:
  - projects

navigation:
  - name: "Notes"
    url: "/notes/"
  - name: "About"
    url: "/about/"

url: https://phillipridlen.com
email: p@rdln.net

assets:
  compression: true
  gzip: true
  digest: true
