name: Lint

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  StandardRB:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmagickwand-dev imagemagick
      - name: "Standard Ruby"
        uses: "standardrb/standard-ruby-action@v1"
        with:
          ruby-version: "3.4.5"
          autofix: false
